ganeti_web/urls.py
# Copyright (C) 2010 Oregon State University et al.
# Copyright (C) 2010 Greek Research and Technology Network
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.

from django.conf.urls.defaults import patterns, url
from haystack.views import SearchView
from django.contrib.auth.decorators import login_required
import os
from forms.autocomplete_search_form import autocomplete_search_form

from ganeti_web.forms.virtual_machine import vm_wizard
from ganeti_web.views.cluster import (ClusterDetailView, ClusterListView,
                                      ClusterVMListView)
from ganeti_web.views.general import AboutView
from ganeti_web.views.jobs import JobDetailView
from ganeti_web.views.node import (NodeDetailView, NodePrimaryListView,
                                   NodeSecondaryListView)
from ganeti_web.views.virtual_machine import (VMDeleteView, VMListView,
                                              VMListTableView)
from ganeti_web.views.vm_template import (TemplateFromVMInstanceView,
                                          VMInstanceFromTemplateView)

cluster_slug = '(?P<cluster_slug>[-_A-Za-z0-9]+)'
cluster = 'cluster/%s' % cluster_slug

primary_node = 'primary_node/(?P<primary_node>.+)'
secondary_node = 'secondary_node/(?P<secondary_node>.+)'

instance = '(?P<instance>[^/]+)'
host = '(?P<host>[^/]+)'

template = '(?P<template>[^/]+)'

# General
urlpatterns = patterns('ganeti_web.views.general',
    #   Index page - it's status page
    url(r'^$', 'overview', name="index"),
    #   Status page
    url(r'^overview/?$', 'overview', name="overview"),
    url(r'^used_resources/?$', 'used_resources', name="used_resources"),
    
    # clear errors
    url(r'^error/clear/(?P<pk>\d+)/?$', 'clear_ganeti_error', name="error-clear"),
    
    # Errors
    url(r'clusters/errors', 'get_errors', name="cluster-errors"),
    #About page
    url(r'^about/?$', AboutView.as_view(), name="about"),
)


# Users - overridden from users app to use custom templates
urlpatterns += patterns('muddle_users.views.user',
    url(r'^accounts/profile/?', 'user_profile', name='profile',
        kwargs={'template':'ganeti/users/profile.html'}),
)

# Users
urlpatterns += patterns('ganeti_web.views.users',
    url(r'^user/(?P<user_id>\d+)/key/?$', 'key_get', name="user-key-add"),

    # ssh keys
    url(r'^keys/get/$',                     'key_get', name="key-get"),
    url(r'^keys/get/(?P<key_id>\d+)/?$',    'key_get', name="key-get"),
    url(r'^keys/save/$',                    'key_save', name="key-save"),
    url(r'^keys/save/(?P<key_id>\d+)/?$',   'key_save', name="key-save"),
    url(r'^keys/delete/(?P<key_id>\d+)/?$', 'key_delete', name="key-delete"),
)

# All SSH Keys
urlpatterns += patterns('ganeti_web.views.general',
    url(r'^keys/(?P<api_key>\w+)/$', 'ssh_keys', name="key-list"),
)

# Clusters
urlpatterns += patterns('ganeti_web.views.cluster',
    #   List
    url(r'^clusters/?$', ClusterListView.as_view(), name="cluster-list"),
    #   List (Paged)
    url(r'^clusters\?page=(?P<page>.+)$', ClusterListView.as_view(), name="cluster-list-paged"),
    #   Add
    url(r'^cluster/add/?$', 'edit', name="cluster-create"),
    #   Detail
    url(r'^%s/?$' % cluster, ClusterDetailView.as_view(),
        name="cluster-detail"),
    #   Edit
    url(r'^%s/edit/?$' % cluster, 'edit', name="cluster-edit"),
    # Refresh
    url(r'^%s/refresh/?$' % cluster, 'refresh', name='cluster-refresh'),
    #   Redistribute config
    url(r'^%s/redistribute-config/?$' % cluster, 'redistribute_config', name="cluster-redistribute-config"),
    #   User
    url(r'^%s/users/?$' % cluster, 'users', name="cluster-users"),
    url(r'^%s/virtual_machines/?$' % cluster, ClusterVMListView.as_view(),
        name="cluster-vms"),
    url(r'^%s/nodes/?$' % cluster, 'nodes', name="cluster-nodes"),
    url(r'^%s/quota/(?P<user_id>\d+)?/?$'% cluster, 'quota', name="cluster-quota"),
    url(r'^%s/permissions/?$' % cluster, 'permissions', name="cluster-permissions"),
    url(r'^%s/permissions/user/(?P<user_id>\d+)/?$' % cluster, 'permissions', name="cluster-permissions-user"),
    url(r'^%s/permissions/group/(?P<group_id>\d+)/?$' % cluster, 'permissions', name="cluster-permissions-group"),

    url(r'^(?P<id>\d+)/jobs/status/?$', "job_status", name="cluster-job-status"),

    #ssh_keys
    url(r'^%s/keys/(?P<api_key>\w+)/?$' % cluster, "ssh_keys", name="cluster-keys"),

    # object log
    url(r'^%s/object_log/?$' % cluster, 'object_log', name="cluster-object_log"),
)


# Nodes
node_prefix = 'cluster/%s/node/%s' %  (cluster_slug, host)
urlpatterns += patterns('ganeti_web.views.node',
    # Detail
    url(r'^%s/?$' % node_prefix, NodeDetailView.as_view(),
        name="node-detail"),
    url(r'^node/(?P<id>\d+)/jobs/status/?$', "job_status", name="node-job-status"),
    
    # Primary and secondary Virtual machines
    url(r'^%s/primary/?$' % node_prefix, NodePrimaryListView.as_view(),
        name="node-primary-vms"),
    url(r'^%s/secondary/?$' % node_prefix, NodeSecondaryListView.as_view(),
        name="node-secondary-vms"),

    #object log
    url(r'^%s/object_log/?$' % node_prefix, 'object_log', name="node-object_log"),

    # Node actions
    url(r'^%s/role/?$' % node_prefix, 'role', name="node-role"),
    url(r'^%s/migrate/?$' % node_prefix, 'migrate', name="node-migrate"),
    url(r'^%s/evacuate/?$' % node_prefix, 'evacuate', name="node-evacuate"),
)

# VM add wizard
urlpatterns += patterns("ganeti_web.forms.virtual_machine",
    url(r"^vm/add/?$", vm_wizard(), name="instance-create"),
)

# VirtualMachines
vm_prefix = '%s/%s' %  (cluster, instance)
urlpatterns += patterns('ganeti_web.views.virtual_machine',
    #  List
    url(r'^vms/$', VMListView.as_view(), name="virtualmachine-list"),
    #  List (Paged)
    url(r'^vms/\?page=(?P<page>.+)$', VMListView.as_view(), name="virtualmachine-list-paged"),

    #  VM Table
    url(r'^%s/vm/table/?$' % cluster, VMListTableView.as_view(),
        name="cluster-virtualmachine-table"),
    url(r'^vm/table/$', VMListTableView.as_view(),
        name="virtualmachine-table"),
    url(r'^vm/table/%s/?$' % primary_node, VMListTableView.as_view(),
        name="vm-table-primary"),
    url(r'^vm/table/%s/?$' % secondary_node, VMListTableView.as_view(),
        name="vm-table-secondary"),

    #  Detail
    url(r'^%s/?$' % vm_prefix, 'detail', name="instance-detail"),
    url(r'^vm/(?P<id>\d+)/jobs/status/?$', 'job_status', name="instance-job-status"),
    url(r'^%s/users/?$' % vm_prefix, 'users', name="vm-users"),
    url(r'^%s/permissions/?$' % vm_prefix, 'permissions', name="vm-permissions"),
    url(r'^%s/permissions/user/(?P<user_id>\d+)/?$' % vm_prefix, 'permissions', name="vm-permissions-user"),
    url(r'^%s/permissions/group/(?P<group_id>\d+)/?$' % vm_prefix, 'permissions', name="vm-permissions-user"),
    
    #  Start, Stop, Reboot, VNC
    url(r'^%s/vnc/?$' % vm_prefix, 'novnc', name="instance-vnc"),
    url(r'^%s/vnc/popout/?$' % vm_prefix, 'novnc',
                        {'template':'ganeti/virtual_machine/vnc_popout.html'},
                        name="instance-vnc-popout"),
    url(r'^%s/vnc_proxy/?$' % vm_prefix, 'vnc_proxy', name="instance-vnc-proxy"),
    url(r'^%s/shutdown/?$' % vm_prefix, 'shutdown', name="instance-shutdown"),
    url(r'^%s/shutdown-now/?$' % vm_prefix, 'shutdown_now',
        name="instance-shutdown-now"),
    url(r'^%s/startup/?$' % vm_prefix, 'startup', name="instance-startup"),
    url(r'^%s/reboot/?$' % vm_prefix, 'reboot', name="instance-reboot"),
    url(r'^%s/migrate/?$' % vm_prefix, 'migrate', name="instance-migrate"),
    url(r'^%s/replace_disks/?$' % vm_prefix, 'replace_disks', name="instance-replace-disks"),

    # Delete
    url(r"^%s/delete/?$" % vm_prefix, VMDeleteView.as_view(),
        name="instance-delete"),

    # Reinstall
    url(r"^%s/reinstall/?$" % vm_prefix, "reinstall", name="instance-reinstall"),
    
    # Edit / Modify
    url(r"^%s/edit/?$" % vm_prefix, "modify", name="instance-modify"),
    url(r'^%s/edit/confirm/?$' % vm_prefix, "modify_confirm", name="instance-modify-confirm"),
    url(r"^%s/rename/?$" % vm_prefix, "rename", name="instance-rename"),
    url(r"^%s/reparent/?$" % vm_prefix, "reparent", name="instance-reparent"),
    
    # SSH Keys
    url(r'^%s/keys/(?P<api_key>\w+)/?$' % vm_prefix, "ssh_keys", name="instance-keys"),
    
    # object log
    url(r'^%s/object_log/?$' % vm_prefix, 'object_log', name="vm-object_log"),
)

# VirtualMachineTemplates
template_prefix = '%s/template/%s' % (cluster, template)
urlpatterns += patterns('ganeti_web.views.vm_template',
    # List
    url(r'^templates/$', 'templates', name='template-list'),
    # Create
    url(r'^template/create/$', vm_wizard(), name='template-create'),
    # Detail
    url(r'^%s/?$' % template_prefix, 'detail', name='template-detail'),
    # Delete
    url(r'^%s/delete/?$' % template_prefix, 'delete', name='template-delete'),
    # Edit
    url(r'^%s/edit/?$' % template_prefix, vm_wizard(), name='template-edit'),
    # Copy
    url(r'^%s/copy/?$' % template_prefix, 'copy', name='template-copy'),
    # Create Instance from Template, and vice versa
    url(r'^%s/vm/?$' % template_prefix, VMInstanceFromTemplateView.as_view(),
        name='instance-create-from-template'),

urls.py
# Copyright (C) 2010 Oregon State University et al.
# Copyright (C) 2010 Greek Research and Technology Network
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.


from django.conf import settings
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('ganeti_web.urls')),
    (r'^', include('object_permissions.urls')),
    (r'^', include('object_log.urls')),
    (r'^', include('muddle_users.urls')),
    (r'^', include('muddle.urls')),

    # user management
    # account/activate/<key>/ - Activate a user
    # account/activate/complete/ - Ater-activation page
    # account/register/ - User registration form
    # account/register/complete/ - After-registration page
    # account/register/closed/ - No registration allowed page
    # ---
    # account/login - login page
    # account/logout - logout page
    # account/password/reset/ - send password reset email
    # account/password/change/ - change current user password

    # Authentication
    url(r'^accounts/login/?', 'django.contrib.auth.views.login',
        name="login",),
    url(r'^accounts/logout/?', 'django.contrib.auth.views.logout',
        {'next_page':'/'}, name="logout"),
    (r'^accounts/', include('registration.urls')),

    # Explicit 500 test route
    (r'^500/$', 'django.views.generic.simple.direct_to_template',
     {'template':"500.html"})
)
# Language settings
urlpatterns += patterns('',
    (r'^i18n/', include('django.conf.urls.i18n')),
    )
handler500 = 'ganeti_web.views.view_500'


#The following is used to serve up local static files like images
urlpatterns += patterns('',
    (r'^favicon.ico', 'django.views.static.serve',
        {'document_root':  settings.STATIC_ROOT, 'path': 'favicon.ico'}),

    # noVNC files
    (r'^novnc/(?P<path>.*)', 'django.views.static.serve',
        {'document_root':  '%s/noVNC/include' % settings.DOC_ROOT}),
)

ganeti_web/forms/autocomplete_search_form.py
# Custom Haystack search form for autocomplete searches

from haystack.forms import SearchForm


class autocomplete_search_form(SearchForm):
    '''
    Custom Haystack search form for autocomplete searches. Important so that
    users can search for 'foo' and get 'foo.bar', 'foo.bar.herp', etc.
    '''
    def search(self):
        '''
        Overwriting SearchForm's default search to implement autocomplete
        searching.
        '''
        if not self.is_valid():
            return self.no_query_found()

        if not self.cleaned_data.get('q'):
            return self.no_query_found()

        # Perform an autocomplete search query on the 'content_auto' fields of
        # the searchable models
        sqs = self.searchqueryset.autocomplete(content_auto=self.cleaned_data['q'])

        if self.load_all:
            sqs = sqs.load_all()

        return sqs

ganeti_web/forms/importing.py
# Copyright (C) 2010 Oregon State University et al.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.


from django import forms

from ganeti_web.models import ClusterUser


class VirtualMachineForm(forms.Form):
    virtual_machines = forms.MultipleChoiceField()
    
    def __init__(self, choices, *args, **kwargs):
        super(VirtualMachineForm, self).__init__(*args, **kwargs)
        self.fields['virtual_machines'].choices = choices


class OrphanForm(VirtualMachineForm):
    """
    Form used for assigning owners to VirtualMachines that do not yet have an
    owner (orphans).
    """
    owner = forms.ModelChoiceField(queryset=ClusterUser.objects.all())


class ImportForm(VirtualMachineForm):
    """
    Form used for assigning owners to VirtualMachines that do not yet have an
    owner (orphans).
    """
    owner = forms.ModelChoiceField(queryset=ClusterUser.objects.all(), required=False)


class NodeForm(forms.Form):
    nodes = forms.MultipleChoiceField()

    def __init__(self, choices, *args, **kwargs):
        super(NodeForm, self).__init__(*args, **kwargs)
        self.fields['nodes'].choices = choices

ganeti_web/views/generic.py
# Copyright (c) 2012 Oregon State University

# Generic class-based view mixins and helpers.

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic.list import ListView

# Standard translation messages. We use these everywhere.

NO_PRIVS = _('You do not have sufficient privileges')


class LoginRequiredMixin(object):
    """
    Helper mixin which applies @login_required to all methods on a view.

    Meant to massively simplify the four-line prelude common to many of our
    views.
    """

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


class PagedListView(ListView):
    """
    Helper which automatically applies uniform pagination options to any
    paginated list.

    This helper should be mixed in *before* ListView or any of its relatives.
    """

    def get_paginate_by(self, queryset):
        """
        Return the number of items to paginate by.

        I like the wording on the other docstring: "An integer specifying how
        many objects should be displayed per page."
        """

        return self.request.GET.get("count", settings.ITEMS_PER_PAGE)

    def paginate_queryset(self, queryset, page_size):
        """
        Returns a 4-tuple containing (paginator, page, object_list,
        is_paginated).

        The Django docstring isn't super-helpful. This function is the actual
        workhorse of pagination. Our hook here is meant to order the queryset,
        if needed, prior to pagination since Django won't do it otherwise.
        """

        if "order_by" in self.request.GET:
            queryset = queryset.order_by(self.request.GET["order_by"])
        return super(PagedListView, self).paginate_queryset(queryset,
                                                            page_size)

ganeti_web/templates/ganeti/virtual_machine/create.html
{% extends "menu_base.html" %}
{% load i18n %}
{% load webmgr_tags %}
{% block title %}{% trans "Create a new Virtual Machine" %}{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css"
            href="{{STATIC_URL}}/css/virtual_machine_create.css"/>
    <link rel="stylesheet" type="text/css"
            href="{{STATIC_URL}}/css/help_tips.css"/>
    <link rel="stylesheet" type="text/css" href="{{SITE_ROOT}}/object_permissions_media/css/form.css"/>

    <!-- javascript includes -->
    <script src="{{STATIC_URL}}/js/disableSingletonDropdown.js"></script>
    <script src="{{STATIC_URL}}/js/createVM_formUpdater.js"></script>
    <script src="{{STATIC_URL}}/js/helpTips.js"></script>
    <script type="text/javascript" src="{{SITE_ROOT}}/object_permissions_media/js/autocomplete_user_search.js"></script>

    <script type="text/javascript">
        
        // -------
        // "main"
        // -------
        $(document).ready(function() {
            /* run when document is fully loaded */
	    var recovery_flag = false;
            if(window.location.pathname.split("/")[window.location.pathname.split("/").length-1] == "recover") { recovery_flag = true; }
            // init the live-form updater
            var frmUpdater = new formUpdater(
                    '{% url instance-create-cluster-choices %}',
                    '{% url instance-create-cluster-options %}',
                    '{% url instance-create-cluster-defaults %}');
            frmUpdater.init({{ cluster_defaults|safe }},recovery_flag);
 
            // init the help tips for the individ. form objects
            initHelpTips('#virtualmachineform');

            // Only display the owner search box if there is more than one valid choice
            if( $.trim($("#id_owner").attr("style")) != "display: none;" )             
            {   autocomplete_user_search($("#id_owner"),'{% url owner-search %}');
            }
        });

    </script>
{% endblock %}

{% block content %}
<div id="virtualmachineform">
    <form method="post" action="{% url instance-create %}">{% csrf_token %}
        <fieldset class="first_fieldset">
            <h1 class="breadcrumb"><span>{% trans "Virtual Machine" %}</span> : {% trans "Create" %}</h1>
            {% vmfield form.owner %}
            {% vmfield form.cluster %}
            {% vmfield form.hypervisor %}
            {% vmfield form.hostname %}
            {% vmfield form.start %}
            {% vmfield form.no_install %}
            {% vmfield form.name_check %}
            {% vmfield form.iallocator %}
            {% vmfield form.iallocator_hostname.as_hidden %}
            {% vmfield form.disk_template %}
            {% vmfield form.pnode %}
            {% vmfield form.snode %}
            {% vmfield form.os %}
        </fieldset>
        <fieldset>
            <legend>{% trans "General Parameters" %} </legend>
            {% vmfield form.vcpus %}
            {% vmfield form.memory %}
            {% if form.disk_type %}
            {% vmfield form.disk_type %}
            {% endif %}
            {% if form.nic_type %}
            {% vmfield form.nic_type %}
            {% endif %}
        </fieldset>

        <fieldset id="disks">
            <h3>{% trans "Disks" %}<div class="icon add"></div></h3>
            {{ form.disk_count }}
            {% for index in form.disk_fields %}
                {% vmfield_disk form index %}
            {% endfor %}
        </fieldset>

        <fieldset id="nics">
            <h3>{% trans "Network Devices" %}<div class="icon add"></div></h3>
            {{ form.nic_count }}
            {% for index in form.nic_fields %}
                {% vmfield_nic form index %}
            {% endfor %}
        </fieldset>

        <fieldset>
            <legend>{% trans "Hypervisor Parameters" %}</legend>
            {% vmfield form.kernel_path %}
            {% vmfield form.root_path %}
            {% if form.serial_console %}
            {% vmfield form.serial_console %}
            {% endif %}
            {% if form.boot_order %}
            {% vmfield form.boot_order %}
            {% endif %}
            {% if form.cdrom_image_path %}
                {% vmfield form.cdrom_image_path %}
            {% endif %}
            {% if form.cdrom2_image_path %}
                {% vmfield form.cdrom2_image_path %}
            {% endif %}
        </fieldset>
        <input class="submit" type="submit" value="{% trans "Create" %}">
    </form>
</div>

<div id="help">
    <h3></h3>
    <div></div>
</div>
<div id="help-contents">
    {% include "ganeti/helptips/vm.html" %}
    {% include "ganeti/helptips/vm_create.html" %}
</div>

{% endblock %}

ganeti_web/templates/ganeti/virtual_machine/create_status.html
{% extends "menu_base.html" %}
{% load webmgr_tags %}
{% load i18n %}
{% block title %} Virtual Machine {{ instance.hostname }}{% endblock %}

{% block head %}

    <script type="text/javascript">
        var job_poller;

        $(document).ready(function() {
            job_poller = new JobPoller();
            var job_status_url = "{% url instance-job-status instance.id %}";
            var cluster_detail_url = "{% url cluster-detail cluster.slug %}";
            job_poller.init(job_status_url, cluster_detail_url, job_complete, job_error);
            job_poller.get_jobs();
        });

        function job_complete() {
            window.location.reload();
        }
        
        function job_error() {
            $("#vm_edit").show();
        }
    </script>
{% endblock %}

{% block content %}
    <h1 class="breadcrumb">
        {% if cluster_admin %}
        <a href="{% url cluster-detail cluster.slug %}#virtual_machines">{{cluster.hostname|abbreviate_fqdn}}</a>
        {% else %}
        <span>{{cluster.hostname|abbreviate_fqdn}}</span>
        {% endif %}
        : <span>{{ instance.hostname }}</span>
        : deploying
    </h1>

    <script type="text/javascript" src="{{STATIC_URL}}/js/job_status.js"></script>

    <ul id="messages"></ul>

    <div id="vm_edit" style="display:none;">
        <ul>
            <li></li><a class="button edit" href="{% url instance-create-recover cluster.slug instance.hostname %}">{% trans "Edit" %}</a></li>
            <li></li><a class="button delete" href="{% url instance-delete cluster.slug instance.hostname %}">{% trans "Delete" %}</a></li>
        </ul>
    </div>



{% endblock %}

ganeti_web/templates/ganeti/virtual_machine/delete.html
{% extends "menu_base.html" %}
{% load webmgr_tags %}
{% load i18n %}

{% block title %}Delete Virtual Machine{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}/css/delete.css"/>
{% endblock %}

{% block content %}

<h1 class="breadcrumb">
    {% if cluster_admin %}
    <a href="{% url cluster-detail cluster.slug %}#virtual_machines">{{cluster.hostname|abbreviate_fqdn}}</a>
    {% else %}
    <span>{{cluster.hostname|abbreviate_fqdn}}</span>
    {% endif %}
    : <a href="{% url instance-detail cluster.slug vm.hostname %}">{{ vm.hostname }}</a>
    : {% trans "Delete" %}
</h1>


<div id="confirm">
    <div class="message">
        Are you sure you want to delete this virtual machine?  This action
        can not be undone.  The virtual machine will be removed from the cluster.
        <ul><li>{{vm.hostname}}</li></ul>
    </div>
    <form method="post" action="{% url instance-delete vm.cluster.slug vm.hostname %}">{% csrf_token %}
        <input id="delete" type="submit" value="Delete" />
    </form>
</div>

{% endblock %}

ganeti_web/templates/ganeti/virtual_machine/reparent.html
{% extends "menu_base.html" %}
{% load webmgr_tags %}
{% load i18n %}
{% block title %}{% trans "Rename" %} Virtual Machine{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css"
            href="{{STATIC_URL}}/css/virtual_machine_create.css"/>
    <link rel="stylesheet" type="text/css"
            href="{{STATIC_URL}}/css/help_tips.css"/>
    <link rel="stylesheet" type="text/css" href="{{SITE_ROOT}}/object_permissions_media/css/form.css"/> 
    <script src="{{STATIC_URL}}/js/helpTips.js"></script>
    <script type="text/javascript" src="{{SITE_ROOT}}/object_permissions_media/js/autocomplete_user_search.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            initHelpTips("#virtualmachineform");
            autocomplete_user_search($("#id_owner"),'{% url owner-search %}');
        });
    </script>
{% endblock %}

{% block content %}
    <div id="virtualmachineform">
        <form method="post">
            {% csrf_token %}
            <fieldset class="first_fieldset">
                <h1 class="breadcrumb">
                    {% if cluster_admin %}
                    <a href="{% url cluster-detail cluster.slug %}#virtual_machines">{{cluster.hostname|abbreviate_fqdn}}</a>
                    {% else %}
                    <span>{{cluster.hostname|abbreviate_fqdn}}</span>
                    {% endif %}
                    : <a href="{% url instance-detail cluster.slug vm.hostname %}">{{ vm.hostname }}</a>
                    : {% trans "Change Owner" %}
                </h1>
                {% vmfield form.owner %}
                <input class="submit" type="submit" value="Save">
            </fieldset>
        </form>
    </div>

    <div id="help">
        <h3></h3>
        <div></div>
    </div>

    <div id="help-contents">
       {% include "ganeti/helptips/vm_create.html" %}
    </div>
{% endblock %}

ganeti_web/templates/ganeti/virtual_machine/vmfield_nic.html
{% load i18n %}
{{ mac.errors }}
{{ mode.errors }}
{{ link.errors }}
<p>
    <label>{% trans "NIC" %}/{{ index }}</label> {{ mac }} {{ mode }} {{ link }}
</p>
<div class="icon delete"></div>